---
- name: "Configure zabbix-server"
  template: src=zabbix_server.conf.j2
            dest=/etc/zabbix/zabbix_server.conf
            owner=zabbix
            group=zabbix
            mode=0644
  notify: zabbix-server restarted
  tags:
    - zabbix-server
    - init
    - config

- name: "Create include dir zabbix-server"
  file: path={{ server_include }}
        owner=zabbix
        group=zabbix
        state=directory
        mode=0644
  tags:
    - zabbix-server
    - init
    - config

- name: "Create zabbix-web directory"
  file: path=/etc/zabbix/web
        owner={{ apache_user }}
        group={{ apache_group }}
        state=directory
        mode=0755
  when: zabbix_web
  tags:
    - zabbix-server
    - init
    - config

- name: "Configure zabbix-web"
  template: src=zabbix.conf.php.j2
            dest=/etc/zabbix/web/zabbix.conf.php
            owner={{ apache_user }}
            group={{ apache_group }}
            mode=0644
  when: zabbix_web
  tags:
    - zabbix-server
    - init
    - config

- name: "Make sure Zabbix Server is running"
  service: name=zabbix-server
           state=started
           enabled=yes
           use=service
