---
# tasks file for wdijkerman.zabbix

- name: "Include OS-specific variables"
  include_vars: "{{ ansible_os_family }}.yml"

- name: "Set short version name"
  set_fact:
      zabbix_short_version: "{{ zabbix_version | regex_replace('\\.', '') }}"
  tags:
    - always

- block:
    - name: Install webserver
      include: install-webserver.yml
      when: zabbix_webserver

    - name: Install Zabbix
      include: install.yml

    - name: Install DB
      include: install-db.yml
      when: zabbix_database

    - name: Configure
      include: configure.yml

  rescue:
    - meta: flush_handlers
